### ISSUE TITLE
请求添加opera的ua，谢谢

### ISSUE THREAD

**Issue by lukemin** [gzlock/simple-extension#1]
请求添加opera的ua，谢谢。或者添加可以设置自己ua的功能。
Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14

**Comment by gzlock** [comment]
OK

lukemin <notifications@github.com> 于 2019年7月17日周三 上午10:15写道：

**Comment by lukemin** [comment]
谢谢

**Comment by gzlock** [comment]
全平台增加Opera UA
再附送一个自定义UA编辑器，GitHub：？？？
![image](https://user-images.githubusercontent.com/2311740/61402519-e5fcee80-a905-11e9-91ea-034a4c2e28df.png)
![image](https://user-images.githubusercontent.com/2311740/61402561-fad98200-a905-11e9-9246-29b96f6caa3c.png)
![image](https://user-images.githubusercontent.com/2311740/61402707-47bd5880-a906-11e9-938c-7f19cece40d1.png)
![image](https://user-images.githubusercontent.com/2311740/61402664-2d837a80-a906-11e9-8311-ea8a032e2c5b.png)

**Comment by gzlock** [comment]
话说我在Chrome扩展商店按错按钮导致这个扩展下架了，新版本等待审核中

**Comment by gzlock** [comment]
中途经历了一次因为缺少隐私政策文档而被拒绝上架的情况，添加隐私政策说明后在Chrome扩展商店已经重新上架了

**Comment by lukemin** [comment]
谢谢
