### ISSUE TITLE
url中带# 匹配异常

### ISSUE THREAD

**Issue by Dev-Wiki** [gzlock/simple-extension#10]
如图:
![image](https://user-images.githubusercontent.com/12946956/190136172-d70066a9-f532-499e-a889-6d750a772c60.png)

![image](https://user-images.githubusercontent.com/12946956/190136195-b4e2e1e1-4827-4962-b812-2c4b21b5fa84.png)

**Comment by gzlock** [comment]
chromium发起网络请求前分析url与跟这个匹配测试工具共用一个js函数，而chromium不会把hash字符串一同发送
```
测试方法你可以试试开着开发者工具=>网络标签页，然后手动打开一个url例如 https://baidu.com/#/a/b/c
可以看到网络请求中的网址没有携带hash字符串
```

https://github.com/gzlock/simple-extension/blob/master/src/js/utils.js#L126
所以使用node.js的url.parse分析网址后没有继续处理url中的hash字符串
为了追求运行效率(每个网络请求都会调用一次这个js函数)，所以跳过了分析hash

说人话就是 chromium发送网络请求时url不会携带hash信息，所以做了分析hash功能也没用🤣

**Comment by Dev-Wiki** [comment]
我这边测试如下, 发起请求后实际的 # 后面的做了处理, 页面内部应该有处理后面的字符串

![image](https://user-images.githubusercontent.com/12946956/190299091-92c07764-2180-4972-a691-29582a2f05ae.png)

**Comment by gzlock** [comment]
因为扩展在对应的api里拿不到hash字符串值，所以涉及到网络请求的url分析里，去分析hash字符串没什么意义

**Comment by Dev-Wiki** [comment]
谢谢 答复, 可以关闭了
