### ISSUE TITLE
[BUG反馈]全局自定义设置（自定义UA列表）刷新后消失

### ISSUE THREAD

**Issue by Mydong** [gzlock/simple-extension#11]
## 作者好，发现一个BUG，添加全局自定义的UA后，

一旦刷新或者重新进入设置；
就会发现列表是空的，看不到任何自己添加的内容信息；

![image](https://user-images.githubusercontent.com/14023137/197508354-65a42e9d-9fe2-4207-b48a-0c5c9a8bb9eb.png)

谷歌浏览器版本：106.0.5249.119 (正式版本) （64 位） (cohort: Stable)

**Comment by CciniSix** [comment]
我也发现了,作者好久不更新了,那么好的插件

**Comment by gzlock** [comment]
已经用v3标准重新开发了这个扩展，正在打包了

**Comment by gzlock** [comment]
chrome扩展商店 和 Edge扩展商店 都在审核中了。

**Comment by gzlock** [comment]
> 我也发现了,作者好久不更新了,那么好的插件

这个扩展我自己是一直在用的，主要用于隐身模式保存cookies
ua这个功能我自己不怎么用，楼主发了issue后准备修补一下
顺便看了一下chrome扩展标准从v2到v3的消息，最后决定以v3标准重新开发。

**Comment by CciniSix** [comment]
> > 我发现，作者好久了，那么那么
> > 的的这个这个这个是是是一直一直一直在在在在在用用用的的的的的一直是是是是是是是是是是是是是，cookie ua cookies 
> > ua ua这个这个这个这个功能功能怎么怎么
> > 怎么看了下chrome扩展标准从v2到v3的消息，最后决定以v3标准重新发布。

大佬威武

**Comment by Mydong** [comment]
> > 我也发现了,作者好久不更新了,那么好的插件
> > 这个扩展我自己是一直在用的，主要用于隐身模式保存cookies
> > ua这个功能我自己不怎么用，楼主发了issue后准备修补一下
> > 顺便看了一下chrome扩展标准从v2到v3的消息，最后决定以v3标准重新开发。

太帅了

**Comment by Mydong** [comment]
> chrome扩展商店 和 Edge扩展商店 都在审核中了。

作者大佬 可以修改修改名称，比如添加一些 关键字，例如 UA切换、user agent switcher之类的。
这么好的插件，这样会有更多人发现。

**Comment by gzlock** [comment]
> > chrome扩展商店 和 Edge扩展商店 都在审核中了。
> 
> 作者大佬 可以修改修改名称，比如添加一些 关键字，例如 UA切换、user agent switcher之类的。 这么好的插件，这样会有更多人发现。

UA和Cookies在行业里都没有用中文表达的，而且也没有找到一个英文词可以表达出包含ua和cookies的意思，就懒得弄了
