### ISSUE TITLE
可以扁平化右键菜单吗？

### ISSUE THREAD

**Issue by void285** [gzlock/simple-extension#12]
因为感觉右键菜单路径太深，之前改了个版本自用，现在看作者更新了，提出来这个想法，也许您能采纳。

![image](https://user-images.githubusercontent.com/612912/204195566-8f153e3f-8c13-4391-90af-f2c9a566853e.png)

**Comment by gzlock** [comment]
0.9.2已实现菜单减层

Leonarda ***@***.***> 于 2022年11月28日周一 下午12:44写道：
