### ISSUE TITLE
Chrome、Edge扩展商店均无法通过审核，并且我看不懂拒审原因，大家来帮忙理解理解？

### ISSUE THREAD

**Issue by gzlock** [gzlock/simple-extension#13]
先说说前提
1. 扩展的数据不会发送、存储到第三方，只使用了浏览器提供的本地存储api，即`chrome.storage.local`
2. 没有任何网络服务器，也就没有个人网站了。
3. 由于这两家都要填写隐私权政策说明，所以我填的是[仓库的这个文件网址](https://github.com/gzlock/simple-extension/blob/master/PrivacyPolicy.md)

### Chrome

![image](https://user-images.githubusercontent.com/2311740/205321823-fe575067-f71a-40ef-a4d5-ca4165b80276.png)

```
违规行为：隐私权政策链接并未指向有效的隐私权政策

纠正方法：确保该链接直接指向隐私权政策页面。（所有者网站不会被视为有效的隐私权政策）

 截图中的两处链接

 [Purple Nickel](https://developer.chrome.com/docs/webstore/troubleshooting/#udp-prominent-disclosure)

[（了解详情）](https://developer.chrome.com/webstore/program_policies#userdata)
```
是指用仓库的markdown文件作为隐私权政策页面 无效吗？

### Edge

截图
![image](https://user-images.githubusercontent.com/2311740/205323254-e26af321-26f1-4f60-8382-35e2aba32fd5.png)

`The Privacy policy that you provided mainly references another browser. Please consider adding Edge browser to the privacy policy and resubmit.`

机翻一下

`您提供的隐私政策主要参考了其他浏览器。 请考虑将 Edge 浏览器添加到隐私政策中并重新提交。`

大家可以看看我的那个隐私说明文件，也只在所用的api里提到了chrome，而事实上edge的api命名空间也是以chrome开头的。

要描述这个扩展是怎么存储用户数据的话，根本绕不过开这个api，也绕不开chrome这个字眼啊

**Comment by gzlock** [comment]
去v2ex提问了

**Comment by yangyunhai** [comment]
哈哈哈  人嘛了，ege审核好严格，我一个浏览器插件，他跟我说 被杀毒软件检测报毒https://etab.store/

**Comment by yonghui666** [comment]
上架扩展商店被拒：对浏览器的新标签页和用户的搜索体验进行更改。有大佬知道怎么解决吗，做了是新标签页扩展

**Comment by gzlock** [comment]
> 上架扩展商店被拒：对浏览器的新标签页和用户的搜索体验进行更改。有大佬知道怎么解决吗，做了是新标签页扩展

可以发邮件的截图看看吗？
自己个人实在找不出问题的话，可以被拒邮件里附带的客服邮件问问情况
