### ISSUE TITLE
Edge隐私模式下，右键不显示插件

### ISSUE THREAD

**Issue by Mark-1215** [gzlock/simple-extension#14]
Edge隐私模式下，右键不显示插件。
如果这个不好改的话，能否把菜单栏上的插件图标加上，保存，切换cookies/ua的功能呢？就跟页面右键一样？
还有设置里面的域名选项卡能否把账号别弄成一列，还跟以前一样，这样找对应账号需要一直翻，比较繁琐。

**Comment by Mark-1215** [comment]
能否把菜单栏上的插件图标加上，保存，切换cookies/ua的功能呢？就跟页面右键一样

**Comment by gzlock** [comment]
因为这个扩展就是为了我自己在edge隐身模式（我只用隐身模式）下保存cookies用的，所以在隐身模式下，扩展的右键菜单一直都可以正常使用的。

但是chrome系的右键菜单api的刷新机制是很糟糕的（一开始做这个扩展的时候就吐槽过），加上从0.9.x开始我缩减了一些权限(这些权限其实也是用来刷新菜单的，但是我觉得没什么必要，也会增加扩展商店的审核时间，就缩减了)，所以这个菜单有可能是有显示问题的，但我遇到的几率很小很小。

你这个问题先检查扩展有没有隐身模式的权限
![image](https://user-images.githubusercontent.com/2311740/208169875-7e6065ec-2391-4f3b-bcfe-4f6f4b96125a.png)

权限正常的话假设某个页面没有扩展菜单或者出现双重菜单，可以通过刷新网页或者切换tab解决的，这个扩展是有通过监听这些事件来强制刷新菜单的。

popup页面（就是点击扩展图标的事件）是有想过做菜单功能的页面的，但是这样一来功能跟菜单实在是重复了，没什么作用啊。

然后设置页面的样式方面，我的使用情况是不会有一个网站会保存超过两个cookies方案的，所以我也不知道你那边的情况是怎么样，可以截个图看看吗

**Comment by gzlock** [comment]
对了，你说的`域名选项卡能否把账号别弄成一列`，这个描述我看不懂
横为行，竖为列，现在设置页面的布局是，域名tab为列排列，cookies方案tab为行排列

**Comment by Mark-1215** [comment]
不好意思打错字了，域名tab为列排列，cookies方案tab为行排列，对，我说的是能否把cookies方案设置为多行多列(以前一个版本就是多行多列)，而不是单行，如果有几十个账号这样翻阅起来非常麻烦。(你这样的初衷是为了更简洁美观，但是账号多了并不适用，你可以适当改回去，或者保留两种方案让用户选择。)

另外一个你说这个权限问题我也是跟你截图一样，不过刚才我又试了一下，取消了权限 然后重新勾选恢复了，希望我这个问题会帮到下一个遇到的人。

小建议：可以加个快速切换上一个账号 跟下一个账号的快捷键就更好了

**Comment by gzlock** [comment]
那还是用回0.8那种排列方法吧

**Comment by gzlock** [comment]
![image](https://user-images.githubusercontent.com/2311740/209407572-ffa697a0-64aa-418a-b7d1-716d5ce98f56.png)
![image](https://user-images.githubusercontent.com/2311740/209407668-877cce5a-57ef-4aee-aeee-f750ca4f4363.png)

找出一种新的刷新菜单的方法了，一个有上百cookies方案的域名也没出问题

域名编辑器也改回旧版的显示方式，绿色项是已使用，浅蓝是点击过的cookies方案

**Comment by gzlock** [comment]
就是在这极端情况下，单级式菜单显得有点沙雕

**Comment by Mark-1215** [comment]
0.8这种排列真心舒服。一眼就看到数据了，看不到CTRL+F也能轻松直观看到。
