### ISSUE TITLE
部分网站无法使用

### ISSUE THREAD

**Issue by Container-Zero** [gzlock/simple-extension#19]
1.[chatgpt](https://chatgpt.com/) 
切换无效，点击菜单中的 cookie 切换无反应，且网站不会自动刷新

2.[hdhive](https://hdhive.online/) 
prompt 显示无内容（似乎变成 alert），如下图：

![image](https://github.com/user-attachments/assets/bb28f663-a730-4b8b-b497-e00a44af011c)

**Comment by gzlock** [comment]
- 问题1是一个小众的历史遗留问题带来的又一个问题，你的issue给了我动力去解决这个历史遗留问题。
不过由于我只有一个openai账号，轻度测试通过（成功保存登录状态，不过似乎很容易触发机器人验证）

- 问题2是缺失了一句文本，大意是：这个网站没有cookies，不能保存。

最新版修复以上问题，两家大扩展商店审核新版本需要时间，期待你的反馈

btw 从v1.0.0开始使用橙色logo区分新版本
![icon_128](https://github.com/user-attachments/assets/c3edc89c-9735-4573-a91f-d54fcc7ed09e)

**Comment by gzlock** [comment]
两家扩展商店都通过审核了

**Comment by Container-Zero** [comment]
经测试故障已修复，感谢您的付出
