### ISSUE TITLE
请问网址改写遇到/全部变成%2F有什么解决方案吗

### ISSUE THREAD

**Issue by xiaohuanshu** [gzlock/simple-extension#4]
网址: http://www.aaa.com/asdf/asdf
规则: http://www.aaa.com/(.*)?
改写: http://www.bbb.com/(.*)?
结果: http://www.bbb.com/asdf%2Fasdf
不应该改写成%2F，请问这个有什么办法吗？

**Comment by gzlock** [comment]
找到问题了，Chrome扩展商店审核更新要几天时间

**Comment by gzlock** [comment]
![image](https://user-images.githubusercontent.com/2311740/71627377-0eb33f00-2c2d-11ea-9fc3-3af600dc22ce.png)
因为路径和查询是分开匹配处理的，所以`/(.*)`没办法匹配到查询

**Comment by xiaohuanshu** [comment]
赞，太感谢了，非常好用的插件~

**Comment by gzlock** [comment]
0.8.30审核通过了，你的解决了吗

**Comment by xiaohuanshu** [comment]
> 0.8.30审核通过了，你的解决了吗

解决了，多谢~
