### ISSUE TITLE
网址改写遇到%变成%25

### ISSUE THREAD

**Issue by ke2020** [gzlock/simple-extension#5]
[https://gzlock.github.io/simple-extension/#preset=eyJ0eXBlIjowLCJ1cmwiOiJodHRwczovL3d3dy5nb29nbGUuY29tL3ZpZGVvP2lkPWdVQXVNUE1WWE5rMVQ5MFNaY0kySU1LdlhnTk9URlVOYklQVlg4bk5iaDI1OVhvMlNCb3dJQnhkZ1d4Zk4lMkYxU2N0WVRlSHU2NTVaeUNjd2hsJTJGcTNFWHN3elBwY2VOQmFNRkRPU0ZJZ2wwbyUzRCZ0eXBlPXBpbiIsInJ1bGUiOiJodHRwczovL3d3dy5nb29nbGUuY29tL3ZpZGVvP2lkPTphJnR5cGU9cGluIiwidmFsdWUiOiJodHRwczovL3d3dy5nb29nbGUuY29tL3ZpZGVvP2lkPTphJnR5cGU9YWJjIn0=](https://gzlock.github.io/simple-extension/#preset=eyJ0eXBlIjowLCJ1cmwiOiJodHRwczovL3d3dy5nb29nbGUuY29tL3ZpZGVvP2lkPWdVQXVNUE1WWE5rMVQ5MFNaY0kySU1LdlhnTk9URlVOYklQVlg4bk5iaDI1OVhvMlNCb3dJQnhkZ1d4Zk4lMkYxU2N0WVRlSHU2NTVaeUNjd2hsJTJGcTNFWHN3elBwY2VOQmFNRkRPU0ZJZ2wwbyUzRCZ0eXBlPXBpbiIsInJ1bGUiOiJodHRwczovL3d3dy5nb29nbGUuY29tL3ZpZGVvP2lkPTphJnR5cGU9cGluIiwidmFsdWUiOiJodHRwczovL3d3dy5nb29nbGUuY29tL3ZpZGVvP2lkPTphJnR5cGU9YWJjIn0=)
本人小白，发现改写后用不了，然后发现value里面的%后面都多了25。

**Comment by gzlock** [comment]
可以说说要改写的link的来源吗，我想实地研究一下
`%2F` 是 `/` 编码后的代替字符，正常来说url是不需要将这个`/`编码的 
```
https://www.google.com/video?id=gUAuMPMVXNk1T90SZcI2IMKvXgNOTFUNbIPVX8nNbh259Xo2SBowIBxdgWxfN%2F1SctYTeHu655ZyCcwhl%2Fq3EXswzPpceNBaMFDOSFIgl0o%3D&type=pin
```

```javascript
decodeURIComponent('https://www.google.com/video?id=gUAuMPMVXNk1T90SZcI2IMKvXgNOTFUNbIPVX8nNbh259Xo2SBowIBxdgWxfN%2F1SctYTeHu655ZyCcwhl%2Fq3EXswzPpceNBaMFDOSFIgl0o%3D&type=pin')
// 结果
// https://www.google.com/video?id=gUAuMPMVXNk1T90SZcI2IMKvXgNOTFUNbIPVX8nNbh259Xo2SBowIBxdgWxfN/1SctYTeHu655ZyCcwhl/q3EXswzPpceNBaMFDOSFIgl0o=&type=pin
```
decode之后也是一个标准的url
所以我想去实地看看情况是怎么样的

**Comment by ke2020** [comment]
> 可以说说要改写的link的来源吗，我想实地研究一下
> `%2F` 是 `/` 编码后的代替字符，正常来说url是不需要将这个`/`编码的
> 
> ```
> https://www.google.com/video?id=gUAuMPMVXNk1T90SZcI2IMKvXgNOTFUNbIPVX8nNbh259Xo2SBowIBxdgWxfN%2F1SctYTeHu655ZyCcwhl%2Fq3EXswzPpceNBaMFDOSFIgl0o%3D&type=pin
> ```
> 
> ![image](https://user-images.githubusercontent.com/2311740/75136650-49fb5700-5720-11ea-8e79-f202e9352725.png)
> decode之后也是一个标准的url

是一个视频网站https://ddrk.me/dorohedoro/?ep=1 ，我用电脑和手机可以看视频，到平板上却不可以，手机和平板的浏览器都是kiwi browser，然后发现手机上获取的是https://v.ddrk.me:9543/video?id=gUAuMPMVXNk1T90SZcI2IMKvXgNOTFUNbIPVX8nNbh259Xo2SBowIBxdgWxfN%2F1SctYTeHu655ZyCcwhl%2Fq3EXswzPpceNBaMFDOSFIgl0o%3D&type=hls ，而平板获取到的是https://v.ddrk.me:9543/video?id=gUAuMPMVXNk1T90SZcI2IMKvXgNOTFUNbIPVX8nNbh259Xo2SBowIBxdgWxfN%2F1SctYTeHu655ZyCcwhl%2Fq3EXswzPpceNBaMFDOSFIgl0o%3D&type=pin ，有试过改UA，不过不行，所以才想到用你的改写网址改最后那个pin为hls，不过目前有这个问题。不懂编程，自己乱试验的，也不知道这么改法行不行，见笑了。

**Comment by gzlock** [comment]
匹配测试工具已经更新了
新版的chrome扩展也提交了审核


另外说一个技巧，你可以使用相对路径模式来做匹配，就不需要填写域名了，具体请看我的例子

https://gzlock.github.io/simple-extension/#preset=eyJ0eXBlIjowLCJ1cmwiOiJodHRwczovL3YuZGRyay5tZTo5NTQzL3ZpZGVvP2lkPWdVQXVNUE1WWE5rMVQ5MFNaY0kySU1LdlhnTk9URlVOYklQVlg4bk5iaDI1OVhvMlNCb3dJQnhkZ1d4Zk4lMkYxU2N0WVRlSHU2NTVaeUNjd2hsJTJGcTNFU0hOY2c1SXhsR2wwVWN0JTJCYVAycUI4JTNEJnR5cGU9cGluIiwicnVsZSI6Ii92aWRlbz9pZD06aWQiLCJ2YWx1ZSI6Ii92aWRlbz9pZD06aWQmdHlwZT1obHMifQ==

**Comment by ke2020** [comment]
google审核有点久😂，想试都没办法

**Comment by gzlock** [comment]
> google审核有点久😂，想试都没办法

因为保存cookies功能和监听url需要的都是很敏感的权限，导致这个扩展要审2天以上

你可以先在url匹配测试工具里玩玩看

**Comment by gzlock** [comment]
审核失败了
脑壳疼
![image](https://user-images.githubusercontent.com/2311740/75544868-cfa03f00-5a5f-11ea-9145-f13ba2a8c921.png)

**Comment by ke2020** [comment]
审核这么严格😑，不过没事，不急，那网站刚好前几天更新，现在平板能看了，不过还是期待你的更新。

**Comment by gzlock** [comment]
应该是以前的扩展截图有Google logo被拒绝了
这次顺便更新了扩展的商店截图，扩展商店的更新已经通过审核了
