### ISSUE TITLE
希望出一个配置同步功能

### ISSUE THREAD

**Issue by icwaos** [gzlock/simple-extension#6]
换电脑配置都不见了，希望作者把配置同步给装上

**Comment by gzlock** [comment]
涉及到cookies这些敏感数据，不太想做远程保存配置这种功能
倒是可以做做导出导入配置文件这个功能

**Comment by gzlock** [comment]
刚刚看了下Google Chrome有扩展配置同步的api，这就开搞

**Comment by icwaos** [comment]
大佬没有放弃项目吧

**Comment by gzlock** [comment]
> 大佬没有放弃项目吧

没有放弃，目前在忙电商项目
扩展的配置数据同步，chrome扩展有api可以直接用 [storage.sync](https://developer.chrome.com/extensions/storage)
但有个疑虑是Chrome没有登录用户的话，这个api还可不可用(是有报错还是怎么的)还需要花时间去测试
考虑到这个需求应该不是很急，就先放放

**Comment by gzlock** [comment]
再多说两句
chrome.storage.sync没有加密，存放cookies的话应该不符合要求(需要考虑到chrome扩展商店的审核要求)
chrome.storage.sync可以存放的数据大小也比storage.local要小
或者做成【导入/导出配置数据】形式代替使用chrome.storage.sync？

**Comment by icwaos** [comment]
如果不符合要求，导入导出也可以，或者可以出一个网盘同步，类似暴力猴那种，另外连2FA两步验证的拓展，Google同步都没有问题，这个cookies应该也问题不大

**Comment by Mark-1215** [comment]
> 

强烈建议 导入/导出配置数据 功能

**Comment by gzlock** [comment]
0.8.33已经把功能添加上了，等待Chrome扩展商店的审核
![image](https://user-images.githubusercontent.com/2311740/95258071-d134af80-0857-11eb-8e05-4f11bf6e54d2.png)

**Comment by gzlock** [comment]
0.8.33翻车了😂，请等待0.8.35
