### ISSUE TITLE
自动升级后数据丢失

### ISSUE THREAD

**Issue by xiaohuanshu** [gzlock/simple-extension#7]
今天发现插件自动更新后，原来的配置都不见了
打开设置发现新版本插件貌似使用了chrome.storage.sync接口存放数据。但老的数据好像没有同步过来。
console里面输入chrome.storage.local.get(null, function (data) { console.info(data) });发现旧数据还在。
把json复制到全局编辑器的数据设置里点导入发现数据也没有更改。

**Comment by gzlock** [comment]
是的，没有做local数据转移到sync功能，因为sync区域有数据容量的配额限制(unlimitedStorage权限只对local生效)
然后0.8.35有你提到的bug，0.8.36已经修复了这个bug但还在审核中(0.8.36也没有做数据转移功能)
等0.8.36审核后，可以再进行这个操作(你的这个操作是正确的，在0.8.36也测试过这个用途并且成功生效)。

**Comment by gzlock** [comment]
然后你的执行代码可以精简为`chrome.storage.local.get(console.log)`

**Comment by xiaohuanshu** [comment]
那是不是最好有个手动触发同步的地方，要不然原来的设置就都没了哈哈

**Comment by gzlock** [comment]
> 那是不是最好有个手动触发同步的地方，要不然原来的设置就都没了哈哈

现在头疼的是sync容量不足的问题。。。我自己的local配置导入到sync会报
`Unchecked runtime.lastError: QUOTA_BYTES_PER_ITEM quota exceeded`错误(sync配额不足)，无解

**Comment by gzlock** [comment]
恐怕只能回退到用local存储了

**Comment by gzlock** [comment]
0.8.37回退到chrome.storage.local了，已经送审了

**Comment by xiaohuanshu** [comment]
更新到0.8.37发现数据回来了，多谢~
