### ISSUE TITLE
关于切换 cookies 的逻辑的一点疑惑

### ISSUE THREAD

**Issue by acbetter** [gzlock/simple-extension#8]
切换 cookies 之前是否会保存当前 cookies 到当前配置文件，然后切换到下个配置文件呢？翻了一下源代码没找到相关逻辑。感谢作者开发这么好用的插件！

**Comment by gzlock** [comment]
切换前没有保存，可以手动保存一次再切换。
一刀切的话，可能会有机会不需要保存再切换cookies的话就没办法不保存切换了不是么

**Comment by acbetter** [comment]
哦哦，情况是这样的，某视频网站使用 cookies 记录视频播放位置，我有多个账号，还是能够希望同步对应账号的视频播放进度。可否把这个需求做成可选项（即用户自己在设置页面设置，是否在切换 cookies 前覆盖当前配置文件），或者我找来到对应位置代码修改并 PR 一下。

**Comment by gzlock** [comment]
这里是保存的
https://github.com/gzlock/simple-extension/blob/68cf9dfad7cc49a37d0442eb1a3b41ab1459de38/src/js/menu.js#L28

这里是切换的
https://github.com/gzlock/simple-extension/blob/68cf9dfad7cc49a37d0442eb1a3b41ab1459de38/src/js/menu.js#L151

可以fork之后改好输出一个package自己用
